🐛 fix: svg import 타입 수정
Neogasogaeseo/Naega-Web pull request #11
Opened 2022-01-07 18:06 UTC by jynam17

## 📋 작업 내용
- [x] costom.d.ts에서 지정한 svg의 타입을 any 말고 적절한 타입으로 수정해주기

## 📌 PR Point
- [웹팩](https://webpack.js.org/guides/typescript/#importing-other-assets)에서 권장한 방법은 맞지만,, no any 실천해보쟈!

## 레퍼런스
https://duncanleung.com/typescript-module-declearation-svg-img-assets/
http://daplus.net/typescript-typescript%EC%97%90%EC%84%9C-svg-%ED%8C%8C%EC%9D%BC%EC%9D%84-%EA%B0%80%EC%A0%B8%EC%98%AC-%EC%88%98-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4/

2022-01-07 18:24 UTC, SeojinSeojin requested changes
https://stackoverflow.com/questions/54121536/typescript-module-svg-has-no-exported-member-reactcomponent

우선 any를 없애는 시도는 정말 좋아!👍👍

원래 리턴되던 친구가 아마도 string값`(src=어쩌구로 쓸 수 있는 친구)`이 포함된 친구일 텐데 FunctionalComponent가 리턴되면 두성 때와 같이 컴포넌트로만 사용될 수 있을 것 같기도 해!! 위에 글에는 그래서 string값도 리턴하는 타입이 있는데 참고해봐도 좋을 것 같아

그리고 요런 수정 사항을 올릴 땐 기존 코드가 잘 작동하는지 확인해주면 좋아!

지금은 이미지 입혀진 코드가 없으니 `App.tsx`같은 데에서 `<img src={icon}/>`으로도 띄워보고 `<Icon/>` 으로도 띄워보면 좋을 것 같아!!

이 리뷰를 받고나서는 
1. 이 코드가 잘 작동하는지 (스트링과 컴포넌트 둘 다로 쓸 수 있는지) 확인해주고
2. 안 된다면 위의 스택오버플로우 참고해주고
3. 스택오버플로우대로 하면 잘 작동하는지 확인해준다면
좋을 것 같아!!!

2022-01-08 05:14 UTC, jynam17 commented
> https://stackoverflow.com/questions/54121536/typescript-module-svg-has-no-exported-member-reactcomponent
> 
> 우선 any를 없애는 시도는 정말 좋아!👍👍
> 
> 원래 리턴되던 친구가 아마도 string값`(src=어쩌구로 쓸 수 있는 친구)`이 포함된 친구일 텐데 FunctionalComponent가 리턴되면 두성 때와 같이 컴포넌트로만 사용될 수 있을 것 같기도 해!! 위에 글에는 그래서 string값도 리턴하는 타입이 있는데 참고해봐도 좋을 것 같아
> 
> 그리고 요런 수정 사항을 올릴 땐 기존 코드가 잘 작동하는지 확인해주면 좋아!
> 
> 지금은 이미지 입혀진 코드가 없으니 `App.tsx`같은 데에서 `<img src={icon}/>`으로도 띄워보고 `<Icon/>` 으로도 띄워보면 좋을 것 같아!!
> 
> 이 리뷰를 받고나서는
> 
> 1. 이 코드가 잘 작동하는지 (스트링과 컴포넌트 둘 다로 쓸 수 있는지) 확인해주고
> 2. 안 된다면 위의 스택오버플로우 참고해주고
> 3. 스택오버플로우대로 하면 잘 작동하는지 확인해준다면
>    좋을 것 같아!!!

오오 알겠읍니다!

2022-01-08 16:11 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-08 16:14 UTC, jynam17 commented
> https://stackoverflow.com/questions/54121536/typescript-module-svg-has-no-exported-member-reactcomponent
> 
> 우선 any를 없애는 시도는 정말 좋아!👍👍
> 
> 원래 리턴되던 친구가 아마도 string값`(src=어쩌구로 쓸 수 있는 친구)`이 포함된 친구일 텐데 FunctionalComponent가 리턴되면 두성 때와 같이 컴포넌트로만 사용될 수 있을 것 같기도 해!! 위에 글에는 그래서 string값도 리턴하는 타입이 있는데 참고해봐도 좋을 것 같아
> 
> 그리고 요런 수정 사항을 올릴 땐 기존 코드가 잘 작동하는지 확인해주면 좋아!
> 
> 지금은 이미지 입혀진 코드가 없으니 `App.tsx`같은 데에서 `<img src={icon}/>`으로도 띄워보고 `<Icon/>` 으로도 띄워보면 좋을 것 같아!!
> 
> 이 리뷰를 받고나서는
> 
> 1. 이 코드가 잘 작동하는지 (스트링과 컴포넌트 둘 다로 쓸 수 있는지) 확인해주고
> 2. 안 된다면 위의 스택오버플로우 참고해주고
> 3. 스택오버플로우대로 하면 잘 작동하는지 확인해준다면
>    좋을 것 같아!!!

React.FC<React.SVGProps<SVGSVGElement>>를 달아도 <Icon /> 형태로는 사용이 안되더라
아무래도 svg를 컴포넌트화 시켜주는건 CRA에서 제공하는 기능이어서 거기서 정해놓은대로 `ReactComponent as`를 해줘야만 하는 것 같고,

그래서
지금 수정한 것처럼 string으로 달아서
`<img src={Icon}/>` 이 형태랑 스컴포넌트 안에서 `content: url(${Icon})` 이 형태 둘 다 되는지 확인함!!

2022-01-08 16:19 UTC, 100Gyeon approved these changes, later dismissed
`<Icon />` 형태로는 사용 x
`<img src={Icon}/>` 형태, `content: url(${Icon})` 형태로 사용하기

너무 좋아! 👀

2022-01-08 16:23 UTC, SeojinSeojin approved these changes, later dismissed
수고 많았수다!!!

2022-01-08 16:23 UTC, SeojinSeojin commented on tsconfig.json
> +  "include": ["src/assets/custom.d.ts"]
이건 머여??!

2022-01-08 16:34 UTC, jynam17 commented on tsconfig.json
> +  "include": ["src/assets/custom.d.ts"]
ㅎ 이것은 사실 이것저것 해보다가 수정해본건데 이거나 전이나 똑같은 것 같고 잘 나오니까,, 그냥 이게 맞겠지? 추측하고 푸시했는데 딱 걸렸군요
지금 다시 원래대로 돌리고 해봤는데 다 잘 돼서 돌려놓을게!

2022-01-08 16:36 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-09 16:10 UTC, Hyoin-Kim approved these changes

2022-01-09 16:12 UTC, 100Gyeon approved these changes

2022-01-09 17:01 UTC, SeojinSeojin approved these changes

2022-01-09 17:06 UTC, merged