팀원소개서 메인 일부, 상세 페이지 실서버 API 붙이기
Neogasogaeseo/Naega-Web pull request #114
Opened 2022-01-18 22:40 UTC by 100Gyeon

## ⛓ Related Issues
- close #113 

## 📋 작업 내용
- [x] [팀원소개서 메인] 나와 관련된 이슈 확인 GET
- [x] [팀원소개서 상세] 팀 정보 GET
- [x] [팀원소개서 상세] 팀 이슈 목록 GET
- [x] [팀원소개서 상세] 나와 관련된 이슈만 보기 GET

## 📌 PR Point
- 나와 관련된 이슈만 볼 수 있게 버튼 클릭하는 부분(`checkMyIssue`)의 코드가 마음에 들지 않네요..

## 👀 스크린샷 / GIF / 링크
메인 페이지 : https://naegasogaeseo-dev.kro.kr/home/team

상세 페이지 : https://naegasogaeseo-dev.kro.kr/team/1

2022-01-18 22:41 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 04:21 UTC, SeojinSeojin requested changes
밤 늦게까지 넘 수고 많았으 👏👏

2022-01-19 04:21 UTC, SeojinSeojin commented on src/infrastructure/api/team.ts
> +  getMyTeamIssue(): Promise<TeamIssueData>;
이름 바꾼거 아주 조아요!

2022-01-19 04:21 UTC, SeojinSeojin commented on src/infrastructure/remote/team.ts
> +        issueListData: response.data.map((team: any) => ({
바꾼거 엄청 많네.. 수고하셨습니당

2022-01-19 04:21 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +      const response = await privateAPI.get({ url: `/team/detail/${teamID}` });
이렇게 받는 과정을 api로 추상화하고 컴포넌트에선 기냥 쓰는건 어떨까유..?

api에는 teamID 값만 던져주고 리턴값을 이렇게 컴포넌트에서 쓰이는 값으로 바꾸는 건 api 단에서 하는 게 좋을 것 같아요!!

만약 목데이터 쓰기가 번거로워서 그랬다면 내가 써주께..

2022-01-19 04:21 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +      const response = await privateAPI.get({ url: `/team/detail/${teamID}` });
아래의 getTeamIssue 했던 것처럼 api로 분리해서 추상화하는게 좋을 것 같아유!!

2022-01-19 04:21 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +  };
checkMyIssue 함수에서는 setIsChecked만 바꿔주고,

isChecked의 변화에 대한 콜백 함수는 useEffect안에서 돌려주면 좋을 것 같아유!

그리고 set할 때도 상태에 직접적으로 접근하기보다는 원래 값을 바꾸는 식이 더 좋을 것 같아유!

```ts
const checkMyIssue = () => setIsChecked(prev => !prev);
```

```ts
useEffect( () => {
    if (teamID === undefined) return;
    if (!isChecked) {
      (async () => {
        const { issueListData } = await api.teamService.getMyIssue(teamID);
        setIssueListData(issueListData);
      })();
    } else {
      (async () => {
        const { issueListData } = await api.teamService.getTeamIssue(teamID);
        setIssueListData(issueListData);
      })();
    }
} , [isChecked, teamID ] )
```

2022-01-19 04:24 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +  };
혹시 여기서 if else 분기 처리하는게 마음에 안 들었던 거라면

https://github.com/Neogasogaeseo/Naega-Web/pull/90

여기서 url에 쓰이는 viewMode 또한 인자로 받은 걸 참고해서 코드를 수정해보면 좋을듯!

2022-01-19 07:19 UTC, jynam17 approved these changes
![image](https://user-images.githubusercontent.com/73823388/150082785-8d75b8ed-c646-4821-adb9-144b7622520d.png)

2022-01-19 08:36 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 08:46 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +  };
오 좋아좋아 고마워 !!

2022-01-19 08:49 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 11:41 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 11:43 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 11:58 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 11:59 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 12:07 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-19 12:08 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +      const response = await privateAPI.get({ url: `/team/detail/${teamID}` });
수정완료 ~~! 고마웡

2022-01-19 12:09 UTC, Hyoin-Kim approved these changes

2022-01-19 12:19 UTC, SeojinSeojin approved these changes
수고하셨습니다!!!!

2022-01-19 12:20 UTC, merged