StyledInput 컴포넌트 구현
Neogasogaeseo/Naega-Web pull request #22
Opened 2022-01-08 17:22 UTC by Hyoin-Kim

## ⛓ Related Issues
- close #21 

## 📋 작업 내용
- [x] StyledInput 구현

## 📌 PR Point
![image](https://user-images.githubusercontent.com/45025551/148653473-250a3402-2b69-4afc-a917-3cb26d15c30d.png)

width, errorMsg, placeholder, maxByte, onChange, onKeyPress 등 필요할때마다 지정 가능하도록 구현하였습니다.

## 👀 스크린샷 / GIF / 링크

## 🔬 Reference
- 구현에 참고한 링크 (필요한 경우만 작성하고 없으면 지우기)

2022-01-08 17:22 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-08 17:31 UTC, SeojinSeojin requested changes
수고하셨습니닷!!! 넘 꼼꼼하게 이것저것 생각하면서 달아준게 느껴졌어여~!~!

2022-01-08 17:31 UTC, SeojinSeojin commented on src/presentation/components/common/StyledInput/index.tsx
> +  message?: string;
요 친구! 용도가 무엇인가여?

2022-01-08 17:31 UTC, SeojinSeojin commented on src/presentation/components/common/StyledInput/index.tsx
> +  maxByte?: number;
요 친구! 아래와 같이 maxLength이면 좋을 것 같아여!!

2022-01-08 17:31 UTC, SeojinSeojin commented on src/presentation/components/common/StyledInput/index.tsx
> +      {!isConditionMet && isInput !== '' && <ErrorMsg>{errorMsg}</ErrorMsg>}
errorMsg가 있는지도 확인해주면 좋을 것 같아여!!

2022-01-08 17:31 UTC, SeojinSeojin commented on src/presentation/components/common/StyledInput/style.ts
> +export const StyledInputWrpper = styled.div`
St만 쓴다고 합니다..!!

2022-01-08 17:31 UTC, SeojinSeojin commented on src/presentation/components/common/StyledInput/index.tsx
> +          placeholder={placeholder}
placeholder 자리에 undefined가 올 수도 있으니 `placeholder && ''`으로 그러한 경우들을 막아주면 좋을 것 가타요!!

2022-01-08 17:39 UTC, Hyoin-Kim commented on src/presentation/components/common/StyledInput/index.tsx
> +  message?: string;
message말씀하시는거라면 없어도 되는겁니다 히히,, 만들려다가 필요없음을 느끼고 지웠어용

2022-01-08 17:41 UTC, Hyoin-Kim commented on src/presentation/components/common/StyledInput/index.tsx
> +          placeholder={placeholder}
오 그럴수도있구나 감사합니당

2022-01-08 17:42 UTC, 100Gyeon commented on src/presentation/components/common/StyledInput/index.tsx
> +    <StyledInputWrpper>
귀여운 오타 발견 !! StInputWrapper로 수정해줘 👀

2022-01-08 17:42 UTC, 100Gyeon commented on src/presentation/components/common/StyledInput/index.tsx
> +interface IProps {
우리 interface 만들 때 I 빼고 만들기로 하지 않았나?

2022-01-08 17:42 UTC, 100Gyeon commented on src/presentation/components/common/StyledInput/style.ts
> +export const Input = styled.input<{ width: string }>`
오오 이런 방법 좋다 👍🏻👍🏻

2022-01-08 17:57 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-09 04:28 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +import { St, InputContainer, Input, ErrorMsg } from './style';
이거 St만 하기로 했다는게 Styled~가 아니라 St~로 접두사를 붙이기로 한거야!

2022-01-09 04:30 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +const StyledInput = ({
컴포넌트는 선언형으로 하기로 했어! function StyledInput(props...) {

2022-01-09 04:32 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +      <InputContainer width={width}>
Container 말고 Wrapper로 통일하기로 했어!

2022-01-09 04:33 UTC, jynam17 commented on src/presentation/components/common/StyledInput/style.ts
> +export const InputContainer = styled.div<{ width: string }>`
스컴포넌트는 다 St 붙이기로 했던거 아닌가..?!

2022-01-09 04:46 UTC, jynam17 approved these changes, later dismissed
이것저것 많이 고려해서 만들어줘서 고마워!

혹시 height는 필요 없을까 ???

2022-01-09 04:53 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +const StyledInput = ({
혹시 이 컴포넌트 스컴포넌트는 아닌데 네이밍이 스컴포넌트 느낌나니까 혹시 CommonInput 이런건 어때?

2022-01-09 04:55 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +interface Props {
Props 인터페이스 이름은 `[컴포넌트명]Props` 이렇게 짓기로 하지 않았나..? 그렇게 기억하는데 적혀있진 않네ㅠㅠ @SeojinSeojin @100Gyeon

2022-01-09 05:10 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +interface Props {
그냥 Props로 하는 것도 괜찮은 방법인 것 같긴 해!

2022-01-09 06:02 UTC, Hyoin-Kim commented on src/presentation/components/common/StyledInput/index.tsx
> +import { St, InputContainer, Input, ErrorMsg } from './style';
아 ㅋㅋ 나 저때 맨정신이 아니어서 생각없이 바꿨네 다시바꿀게ㅜㅜ

2022-01-09 06:03 UTC, Hyoin-Kim commented on src/presentation/components/common/StyledInput/index.tsx
> +interface Props {
너무 헷갈려서 일단 다시 반영해서 푸쉬할게,,! 근데 아마 밤에 반영해서 올릴수있을것같아ㅜㅜ

2022-01-09 06:05 UTC, Hyoin-Kim commented on src/presentation/components/common/StyledInput/index.tsx
> +interface Props {
height 안만든 이유는 input 태그라서,,! 그외에 height가 필요한 태그는 더 긴 텍스트를 입력하는 textarea를 사용할것같아서 width만 만들었어!!

2022-01-09 08:48 UTC, 100Gyeon commented on src/presentation/components/common/StyledInput/index.tsx
> +interface Props {
@jynam17 맞아맞아 `[컴포넌트명]Props`로 하기로 했었어!

2022-01-09 13:37 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +interface Props {
@Hyoin-Kim 아하!! 그러면 textarea에도 적용할 수 있게 스타일만 따로 상수 지정해서 쓰면 좋을 것 같은데 내가 상수 만들고 푸시 한 뒤에 이 컴포넌트에 그 스타일 부분만 상수로 대치해놔도 괜찮을까??

2022-01-09 15:58 UTC, 100Gyeon commented on src/presentation/components/common/StyledInput/style.ts
> +export const InputContainer = styled.div<{ width: string }>`
맞아!

2022-01-09 16:08 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-09 16:08 UTC, Hyoin-Kim commented on src/presentation/components/common/StyledInput/index.tsx
> +interface Props {
오키오키!!!

2022-01-09 16:12 UTC, 100Gyeon approved these changes, later dismissed

2022-01-09 16:54 UTC, SeojinSeojin submitted a review, later dismissed

2022-01-09 16:59 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +      <StInputContainerWrapper width={width}>
여기를 StInputWrapper로 바꿔쥬구

2022-01-09 16:59 UTC, jynam17 commented on src/presentation/components/common/StyledInput/index.tsx
> +    <StInputWrapper>
여기를 StStyledInput으로 바꿔주면 돼!

2022-01-09 17:05 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-09 17:06 UTC, 100Gyeon approved these changes

2022-01-09 17:38 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-09 17:38 UTC, SeojinSeojin approved these changes

2022-01-09 17:48 UTC, jynam17 approved these changes

2022-01-09 17:49 UTC, merged