너가소개서/팀원소개서/마이페이지 Header
Neogasogaeseo/Naega-Web pull request #32
Opened 2022-01-10 12:12 UTC by 100Gyeon

## ⛓ Related Issues
- close #28 

## 📋 작업 내용
- [x] Header 구조화 및 스타일링

## 📌 PR Point
- 모든 a 태그의 text-decoration을 없애는 게 좋을 것 같아서 GlobalStyle 추가했습니다.
- 더 좋은 구현 방법이 있다면 리뷰 남겨주세요~!

## 👀 스크린샷 / GIF / 링크
<img src="https://user-images.githubusercontent.com/58380158/148763802-55973c46-9981-41d7-b7e9-5c1c32d67e68.gif" width="300px">

2022-01-10 12:12 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 12:26 UTC, jynam17 commented on src/assets/images/index.ts
> +export { default as imgLogo } from './img_logo.svg';
💟✨💓

2022-01-10 12:32 UTC, Hyoin-Kim approved these changes
수고많았어 ~ 코드 야무지게 잘짰넹

2022-01-10 12:32 UTC, Hyoin-Kim commented on src/assets/images/index.ts
> +export { default as imgLogo } from './img_logo.svg';
바꿔줬구낭 ㅎㅎ고마워~

2022-01-10 12:32 UTC, Hyoin-Kim commented on src/presentation/components/common/Header/style.ts
> +    }
이 태그 어디에서 쓰는거징

2022-01-10 12:33 UTC, 100Gyeon commented on src/presentation/components/common/Header/style.ts
> +    }
이거 NavLink 부분에서 a 태그로 쓰여!

2022-01-10 12:33 UTC, SeojinSeojin requested changes
우리가 리액트와 스타일드 컴포넌트를 사용하고 있는데 엘리먼트의 id나 style에 바로 접근하는건 막 권장되지는 않을  것이야..!!

내가 다른 방법을 제안해볼게!!

```tsx
const [currentTab, setCurrentTab] = useState(pageName.match("\/(?:.(?!\/))+$")[0]);

const tabs = [ { name:'너가소개서', href="home"}, {name:'팀원소개서', href="team", ...}]

...

tabs.map(tab => 
<NavLink 
	to={`/home/${tab.href}`} 
	onClick={()=>setSelectedTab(tab.href)} 
	isSelected={selectedTab === tab.href}
>
	{tab.name}
</NavLink>)
```

이런 방식은 어떨까!

2022-01-10 12:33 UTC, SeojinSeojin commented on src/presentation/components/common/Header/index.tsx
> +      prevPage.style.borderBottom = `none`;
바로 style에 접근하는 것보다 Styled Component의 프롭으로 `isCurrent`이라는 값을 주고 그 값에 따라 스타일을 바꿔주는건 어떨까?

2022-01-10 12:33 UTC, SeojinSeojin commented on src/presentation/components/common/Header/index.tsx
> +  const [prev, setPrev] = useState('');
이 친구는 용도가 먼가요?

current라는 값만 있어도 스타일 지정하는 데엔 문제 없을 것 같아요..!!

2022-01-10 12:36 UTC, 100Gyeon commented on src/presentation/components/common/Header/index.tsx
> +      prevPage.style.borderBottom = `none`;
좋아좋아 나도 직접 접근하는 부분이 마음에 걸려서 수정하고 싶었어😂 방법 참고해서 바꿔볼게!

2022-01-10 12:37 UTC, Hyoin-Kim commented on src/presentation/components/common/Header/index.tsx
> +      prevPage.style.borderBottom = `none`;
나도 스타일컴포넌트로 넘겨주는건 어떨지 고민하다가 나도 저렇게 코드짤것같아서 그대로 놔뒀는데,,,ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ

2022-01-10 12:38 UTC, 100Gyeon commented on src/presentation/components/common/Header/index.tsx
> +  const [prev, setPrev] = useState('');
클릭한 부분에 스타일 적용해 주고, 아닌 부분에 스타일 빼주고 싶어서 나눠서 생각했는데 이것도 같이 수정해야겠다 !!

2022-01-10 12:43 UTC, jynam17 commented on src/presentation/components/common/Header/index.tsx
> +      prevPage.style.borderBottom = `none`;
친구들이 말한거랑 같은 맥락으로 요런 식으로 어때!!
```tsx
const StNavLink = styled(NavLInk)<{ isSelected: boolean }>`
` 
```

2022-01-10 12:44 UTC, jynam17 commented on src/presentation/components/common/Header/style.ts
> +    }
NavLink도 a구나!!

2022-01-10 16:33 UTC, jynam17 approved these changes

2022-01-10 16:38 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 16:39 UTC, 100Gyeon commented on src/presentation/components/common/Header/index.tsx
> +      prevPage.style.borderBottom = `none`;
그 방법도 좋지 ✔

2022-01-10 16:42 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 17:04 UTC, SeojinSeojin approved these changes
수과셨습니다!!!✨✨✨✨

2022-01-10 17:04 UTC, SeojinSeojin commented on src/presentation/components/common/Header/index.tsx
> +            className={currentTab === tab.href ? 'current' : ''}
styled component가 자동으로 className을 만들어주니까 우리 단에서 클래스이름을 부여하는 것이 좋지 않을 수 있을 것 같아..!!!

currentTab === tab.href 이 친구를 isSelected라는 prop으로 넘기면 좋을 것 같다!!

2022-01-10 17:04 UTC, SeojinSeojin commented on src/presentation/components/common/Header/index.tsx
> +function Header() {
이 친구 Home에서 쓰이니까 HomeHeader 해주면 어떨까?

![image](https://user-images.githubusercontent.com/48249505/148807159-5f12aec7-baa4-42fc-b4f5-e80913e0ce05.png)
이 친구와 이름이 헷갈릴 수 있을듯..!!

2022-01-10 18:24 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 18:27 UTC, 100Gyeon commented on src/presentation/components/common/Header/index.tsx
> +function Header() {
다른 곳에도 헤더가 있구나 ㅠㅠ 수정할게!

2022-01-10 18:27 UTC, 100Gyeon commented on src/presentation/components/common/Header/index.tsx
> +            className={currentTab === tab.href ? 'current' : ''}
좋은 방법이야 고마워 서진아 😉

2022-01-10 19:21 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 21:00 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-11 07:18 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-11 08:12 UTC, SeojinSeojin approved these changes
수고하셨습니다!!!👍

2022-01-11 08:12 UTC, SeojinSeojin commented on src/presentation/components/common/Header/index.tsx
> +            onClick={() => setCurrentTab(tab.href)}
위의 useEffect에서 location이 바뀔 때마다 currentTab이 바뀌게 해뒀는데

그럼 이 부분은 없어도 괜찮지 않을까?

이 친구가 눌리면 location이 tab.href로 바뀌니까!

2022-01-11 08:19 UTC, jynam17 commented on src/presentation/components/common/Header/index.tsx
> +          >
와 진짜 멋지게 짰다 !!!!!!!

2022-01-11 09:14 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-11 09:15 UTC, 100Gyeon commented on src/presentation/components/common/Header/index.tsx
> +            onClick={() => setCurrentTab(tab.href)}
그러네~! 나중에 useEffect 추가하면서 아래 코드까지 고려를 못했다 고마워 👍🏻

2022-01-11 09:41 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-11 09:53 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-11 11:54 UTC, merged