로그인/회원가입 뷰 구현
Neogasogaeseo/Naega-Web pull request #39
Opened 2022-01-10 19:50 UTC by Hyoin-Kim

## ⛓ Related Issues
- close #5 

## 📋 작업 내용
- [x] 로그인 뷰 구현
- [x] 회원가입 뷰 구현

## 📌 PR Point
- 공통적으로 사용하는 CommonInput에 @추가를 위한 img 를 추가하였습니다.
- 추후에 서버 api연결때 사용할 변수(image, setIsConditionMet)는 현재 사용하지 않아 첫번째줄에 /* eslint-disable @typescript-eslint/no-unused-vars */ 추가해뒀습니당

## 👀 스크린샷 / GIF / 링크
- 로그인 기능
 
![Animation28](https://user-images.githubusercontent.com/45025551/148829307-864c5201-208f-48e7-9748-d6018ad9a29c.gif)

- 회원가입 기능

![Animation29](https://user-images.githubusercontent.com/45025551/148829328-08212b13-3ef2-4a21-8ca2-f23ad55b39a6.gif)

2022-01-10 19:57 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 20:15 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 20:21 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-10 20:27 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-11 08:21 UTC, SeojinSeojin requested changes
수과셨습니다~!~!✨👍💖

2022-01-11 08:21 UTC, SeojinSeojin commented on src/presentation/components/LoginForm/OAuth.ts
> +export const KAKAO_AUTH_URL = `https://kauth.kakao.com/oauth/authorize?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&response_type=code`;
이건 .env 파일을 만들어서 숨기는게 좋을 것 같아유..
REDIRECT_URI, KAKAO_AUTH_URL은 괜찮은데 CLIENT_ID는.. 소중한 정보니까!

https://m.blog.naver.com/legend25/222033372402
이 글을 참고해서 수정해주셔용

2022-01-11 08:21 UTC, SeojinSeojin commented on src/presentation/pages/Join/index.tsx
>  const index = () => {
이 친구 이름이 index인데 이름을 JoinPage 같은 것으로 바꿔줘야 좋을 것 같아요!!

2022-01-11 14:27 UTC, jynam17 commented on src/presentation/components/JoinForm/index.tsx
> +function index() {
컴포넌트 명으로 수정해주기!!

2022-01-11 14:28 UTC, jynam17 commented on src/presentation/components/JoinForm/index.tsx
> +    <StJoinWrapper>
St[컴포넌트명]으로 바꿔쥬면 고마워!

2022-01-11 14:31 UTC, jynam17 commented on src/presentation/components/LoginForm/index.tsx
> +const index = () => {
여기듀 컴포넌트 명으루!!

2022-01-11 14:32 UTC, NamJwong commented on src/presentation/components/LoginForm/style.ts
> +import styled from 'styled-components';
가장 바깥 컴포넌트 - St[컴포넌트명]
그외 스타일 컴포넌트 - St만 앞에 붙여주기
수정 부탁해!

2022-01-11 14:36 UTC, jynam17 reviewed
고생 많았오 !!

2022-01-11 14:40 UTC, 100Gyeon commented on src/presentation/components/JoinForm/style.ts
> +  color: #909090;
color: ${COLOR.GRAY_5};로 바꿔주세용 ~!

2022-01-11 14:45 UTC, 100Gyeon commented on src/presentation/components/LoginForm/style.ts
> +    color: #ff6262;
color: ${COLOR.CORAL_MAIN};으로 수정하기!

2022-01-11 14:52 UTC, 100Gyeon reviewed
우리 이제 카카오 로그인도 있고 멋져..✨ 수고했어 !!

2022-01-11 14:55 UTC, jynam17 approved these changes

2022-01-12 07:21 UTC, SeojinSeojin approved these changes
수고하셨숩니당~!!!

![image](https://user-images.githubusercontent.com/48249505/149081855-82b66989-469c-4a25-ab4e-59b730632a61.png)

2022-01-12 07:24 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-12 07:33 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-12 10:02 UTC, closed without merging