팀원소개서 이슈 카드 리스트
Neogasogaeseo/Naega-Web pull request #51
Opened 2022-01-12 21:49 UTC by 100Gyeon

## ⛓ Related Issues
- close #29 

## 📋 작업 내용
- [x] 피드백 남긴 인원의 프로필 이미지를 최대 3개 포함하고 있는 `IssueMemberList` 컴포넌트 구조화 및 스타일링
- [x] 팀 프로필과 사용자 이름을 포함하고 있는 `IssueTeamInfo` 컴포넌트 구조화 및 스타일링
- [x] `IssueCard`, `IssueCardList` 컴포넌트 구조화 및 스타일링
- [x] 이슈 카드 누르면 상세(피드백) 페이지로 이동하도록 구현

## 📌 PR Point
### [궁금한 점]
- 리액트 최적화를 위해서 index를 사용하지 않는 것이 좋다고 배웠는데,
unique key를 만들기 위해서 아래와 같이 작성하게 되었습니다. 더 좋은 방법이 없을까요😥

  ```typescript
  <div>
    {issueMembers.slice(0, MAX_IMAGE_NUM).map((member, index) => (
      <img key={`Team ${id}-Issue ${issueNumber}-Index ${index}`} src={member} />
    ))}
  </div>
  ```

### [기타]
- 로고 클릭했을 때 "/home/neoga"로 이동할 수 있도록 you -> neoga 수정
- `font-size: ${size};`에 px이 없어서 `font-size: ${size}px;`로 변경

  ```typescript
  export const FONT = ({ size, weight, position }: Font) => css`
    font-size: ${size}px;
    font-weight: ${getFontWeight(weight)};
    letter-spacing: ${getLetterSpacing(position)};
  `;
  ```

## 👀 스크린샷 / GIF / 링크
<img src="https://user-images.githubusercontent.com/58380158/149222118-5b4fa15f-ee1f-4a30-9fea-9b81d4729aef.png" width="200px">

2022-01-12 21:49 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-13 03:03 UTC, SeojinSeojin requested changes
새벽 6시라니.. 넘 수고했어ㅜㅜㅜㅜ
컴포넌트 안에 데이터 있는 부분들만 분리하면 될듯!!👍✨

2022-01-13 03:03 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +  const issueListData = [
여기서 데이터를 받기보다는 목데이터로 받아오는 방식을 써봐야 할 것 같아!! 
이렇게 하면 여기서 쓴거랑 서버에서 준거랑 변수명 등이 다를 때 다시 처리하는 것도 번거롭고 바꿀 내용들이 많아질 것 같아!

https://github.com/Neogasogaeseo/Naega-Web/pull/43
https://github.com/Neogasogaeseo/Naega-Web/pull/23

이 두 개 참고해서 함 해볼래?

1. infrastructure 폴더의 api의 team.ts에 getTeamIssue(teamID: string) : Promise<TeamIssueData> 이런 식으로 멤버 함수를 만들어주고
2. types의 team.ts에 요청 응답 값으로 받을 값들을 정의해주고 (밑에 있는 프롭들을 그대로 인터페이스로 따면 될듯!)
3. 여기 있는 목데이터를 싹다 mock의 team.data.ts에 TEAM_ISSUE_INFO를 만들어서 옮겨주고
4. mock의 team.ts에 getTeamIssueInfo 함수를 만들어서 리턴한 다음에
5. 이 컴포넌트 안에서는 async 요청으로 받아오기만 하면 될듯해!!

2022-01-13 03:03 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +      issueNumber: 1,
id랑 issueNumber이 둘 다 있어야 할 이유가 있을까?
하나만 있어도 괜찮을 것 같아!!

2022-01-13 03:03 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +    navigate(`/team/${id}/${issueNumber}`);
id 말고 teamID를 넘겨줘야 할 것 같아!! 여기서 id는 이슈의 아이디니까... 

`팀아이디/이슈아이디` 이렇게 되어야 하는데 `이슈아이디/이슈아이디`로 넘어가는 것 같아!

2022-01-13 03:03 UTC, SeojinSeojin commented on src/presentation/style/common/font-style.ts
> +  font-size: ${size}px;
와아앙 고쳐주어서 고마우이~!!!!

2022-01-13 03:03 UTC, SeojinSeojin commented on src/presentation/pages/Home/Team/index.tsx
> +  const issueListData = [
이거도 마찬가지로 여기서 선언하지 말고 api에서 받아와서 비동기로 처리하는 방식을 써봐야 할 것 같아!!

2022-01-13 05:11 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +  const issueListData = [
좋아좋아 목데이터 사용해볼게 !!

2022-01-13 05:15 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +      issueNumber: 1,
나는 id를 teamID로 생각하고 줬는데 수정해 볼게 !!

2022-01-13 05:25 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-13 05:39 UTC, Hyoin-Kim approved these changes
달리느라 고생많았어ㅜ~~!!!

2022-01-13 05:39 UTC, Hyoin-Kim commented on src/presentation/components/common/IssueTeamInfo/style.ts
> +  }
요거는 어디에 사용되는 스타일이야,? * + * 요게 몬지 궁금해

2022-01-13 05:39 UTC, Hyoin-Kim commented on src/presentation/pages/Team/Main/index.tsx
> +  const issueListData = [
나도 참고해야겠다~~

2022-01-13 05:46 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-13 06:07 UTC, jynam17 reviewed
질문 답변!
그냥 리스트의 키로만 쓰이는거라면 그정도로 해도 괜찮을 것 같아요!!

2022-01-13 06:10 UTC, 100Gyeon commented on src/presentation/components/common/IssueTeamInfo/style.ts
> +  }
<img src="https://user-images.githubusercontent.com/58380158/149274949-99fe9ef5-af40-4e78-bfe1-bbbd8186163f.png" width="200px">

나는 이 컴포넌트 안에 들어있는 모든 태그들의 간격을 6px로 설정하려고 썼어!
인접 형제 결합자(+) 쓰면 한꺼번에 간격 조정할 때 유용해 👍🏻

2022-01-13 06:12 UTC, jynam17 reviewed
아이폰 사파리에서 확인해봤는데 완벽하네유!! 멋져!

2022-01-13 06:22 UTC, Hyoin-Kim commented on src/presentation/components/common/IssueTeamInfo/style.ts
> +  }
와 신기하다 고마워 알려줘서!!!

2022-01-13 06:25 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 ! <a href="naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~

2022-01-13 06:35 UTC, jynam17 approved these changes

2022-01-13 06:35 UTC, jynam17 commented on src/presentation/components/common/IssueCardList/index.tsx
> +          {...issue}
omg 이렇게 할 수 있구나

2022-01-13 06:38 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 06:50 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 08:03 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 08:10 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 08:48 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 09:00 UTC, SeojinSeojin requested changes
데이터 넘 잘 달았다..!! 수고 많았우!!!!1
대신 실제로 서버 통신을 할 때는 `teamID`가 필요할 것 같아서 그걸 미리 넘겨주어야 할 것 같아!!

2022-01-13 09:00 UTC, SeojinSeojin commented on src/infrastructure/api/team.ts
> +  getTeamIssue(): Promise<TeamIssueData>;
팀 프로필이랑 이슈를 받으려면 팀 번호가 있어야 할 것 같아!!
파라미터로 teamID:string을 줘야 할듯해!

2022-01-13 09:00 UTC, SeojinSeojin commented on src/presentation/components/common/IssueCard/index.tsx
> +  onIssueClick: (id: number, issueNumber: number) => void;
teamID면 나중에 알아보기 편할 것 가타유~

2022-01-13 09:00 UTC, SeojinSeojin commented on src/presentation/components/common/IssueMemberList/index.tsx
> +  const MAX_IMAGE_NUM = 3;
상수로 뺀거 진짜 잘했닷!!!

2022-01-13 09:02 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 09:04 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 09:07 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 09:23 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="htts://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 09:23 UTC, 100Gyeon commented on src/infrastructure/api/team.ts
> +  getTeamIssue(): Promise<TeamIssueData>;
팀 상세 페이지 만들 때 참고할게 고마워 ㅎㅎ

2022-01-13 09:24 UTC, 100Gyeon commented on src/presentation/components/common/IssueCard/index.tsx
> +  onIssueClick: (id: number, issueNumber: number) => void;
헉 다 바꾼 줄 알았는데 여기도 남아있었구나 고마워 !!!! 꼼꼼해 😘

2022-01-13 09:24 UTC, SeojinSeojin approved these changes

2022-01-13 09:24 UTC, SeojinSeojin commented on src/infrastructure/api/team.ts
> +  getTeamIssue(): Promise<TeamIssueData>;
미안혀... 고마워....

2022-01-13 09:25 UTC, SeojinSeojin commented
![image](https://user-images.githubusercontent.com/48249505/149302444-bdbd208c-ef64-4f64-a88e-c66117b11862.png)
![image](https://user-images.githubusercontent.com/48249505/149302494-044f2b10-2068-437f-8811-13f7632714f4.png)

2022-01-13 09:26 UTC, SeojinSeojin commented
![image](https://user-images.githubusercontent.com/48249505/149302634-c6710d9d-2725-4bc8-8771-6158ae4f396d.png)
![image](https://user-images.githubusercontent.com/48249505/149302689-9a1b16e1-437e-4bf6-889c-85f780c1928b.png)

2022-01-13 09:26 UTC, merged