팀 상세 페이지
Neogasogaeseo/Naega-Web pull request #66
Opened 2022-01-13 18:25 UTC by 100Gyeon

## ⛓ Related Issues
- close #52 

## 📋 작업 내용
- [x] 화면 상단 팀 프로필 부분(사진, 이름, 팀 소개, 멤버 수, 이름) 구조화 및 스타일링
- [x] 이슈 추가 버튼 : 버튼 스타일 상수 사용, 이슈 등록 페이지로 이동
- [x] 팀 수정 버튼 : 팀 등록 페이지로 이동
- [x] 체크박스 누르면 색깔 변경
- [x] 이슈 카드 리스트 컴포넌트 재사용
- [x] mock data 사용

## 📌 PR Point
- 이슈 등록 페이지로 이동하는 코드를 짜는 과정에서 `TeamRouter`를 변경했습니다.

## 👀 스크린샷 / GIF / 링크
https://naegasogaeseo-dev.kro.kr/team/0

https://naegasogaeseo-dev.kro.kr/team/1

<img src="https://user-images.githubusercontent.com/58380158/149387621-766f4d07-2805-4e5a-89e3-997d6fdec816.png" width="200px">

2022-01-13 18:27 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 18:31 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-13 18:52 UTC, SeojinSeojin requested changes
수고하셨습니다~!~!~!
목데이터도 넘 잘 입히고 UI도 진짜 세세하구만~!!~~

리뷰 받은 부분만 조금 손보면 될듯해요~!~

2022-01-13 18:52 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +  useEffect(() => {
이걸 18~27번째 줄에 있는 useEffect 안에 같이 넣어주어도 될 것 같아요!!

2022-01-13 18:52 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +  ));
바로 컴포넌트 안에다가 해도 괜찮을 것 같아!!

return 위에 있는 친구들은 진짜 많이 호출되는데
이 부분에 console.log 찍어보면 진짜 많이 로그 찍힐거야!!

얘네는 members라는 값에만 의존하고 있는데,(===members라는 값에 따라서 변화가 있으면 되는데)
return 위에다가 쓰면은 오만가지 state변화에 다시 다 리렌더링이 될거야..!!

로그 찍히는 만큼 얘네가 계속 호출되는 건데 이 친구들이 그렇게 많이 호출되어야 하는 애들이 아니니까
바로 컴포넌트 안에 넣어줘야 좋을 것 같아!

2022-01-13 18:52 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +      const infoData = await api.teamService.getTeamInfo(teamID);
```tsx
const { teamInfoData } = await api.teamService.getTeamInfo(teamID);
```

이렇게 받아서 뎁쓰를 한방 줄이는건 어떨까?
굳이 `teamInfoData.teamInfoData`로 두 번 들어가야 할 필요는 없을 것 같아..!!

2022-01-13 18:52 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +  const members = teamInfoData?.teamInfoData[Number(teamID)].teamMembers;
1. 이 친구들도 컴포넌트 안에서 선언되는게 좋을 것 같아!!
2. `Number(teamID)` 대신 `+teamID`로 쓸 수도 있다!

2022-01-13 18:52 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +          {team.teamImage ? <img src={team.teamImage} /> : <img src={imgEmptyProfile} />}
예외처리 아주 조하~~~

```tsx
<img src={team.teamImage ?? imgEmptyProfile} />
```

이렇게 src 안에서 예외처리하고 ??이라는 친구를 써보아도 좋을 것 같아!!

2022-01-13 18:52 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/style.ts
> +      ${FONT_STYLES.R_13_TITLE};
꼼꼼하게 잘 적용하고 있구만~~ 굿굿!!!!

2022-01-14 04:57 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +  useEffect(() => {
좋아좋아 !!

2022-01-14 04:57 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +      const infoData = await api.teamService.getTeamInfo(teamID);
안 그래도 이거 거슬렸는데 넘 좋다 !!

2022-01-14 04:58 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/style.ts
> +      ${FONT_STYLES.R_13_TITLE};
저렇게 쓰니까 아주 편해 😘

2022-01-14 04:59 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +          {team.teamImage ? <img src={team.teamImage} /> : <img src={imgEmptyProfile} />}
src 안에서 예외 처리 하는 게 더 좋겠다 ✔

2022-01-14 05:19 UTC, jynam17 approved these changes
지연이 고생해쏘💟

2022-01-14 05:20 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 06:52 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +  ));
서진아 디코 한번 확인해줘 ~!

2022-01-14 07:34 UTC, Hyoin-Kim approved these changes

2022-01-14 07:34 UTC, Hyoin-Kim commented
고생많았어 지연이~~~~~~~

2022-01-14 07:41 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 08:03 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 08:11 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 08:34 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 08:59 UTC, SeojinSeojin approved these changes
진짜 수고많았오... 

방금 리뷰 단 부분 반영하고 싶음 해주어~

2022-01-14 08:59 UTC, SeojinSeojin commented on src/infrastructure/api/team.ts
> +  getTeamInfo(teamID: string): Promise<TeamInfoData>;
넘 수고해쏘....

2022-01-14 08:59 UTC, SeojinSeojin commented on src/presentation/pages/Team/Main/index.tsx
> +          {isChecked ? <img src={icCoralCheck} /> : <img src={icGrayCheck} />}
이 친구도 src 안에서 삼항연산자 해도 괜찮을듯해!!

2022-01-14 09:28 UTC, 100Gyeon commented on src/presentation/pages/Team/Main/index.tsx
> +          {isChecked ? <img src={icCoralCheck} /> : <img src={icGrayCheck} />}
좋아좋아 같이 바꿔야겠다 !! 👍🏻

2022-01-14 09:30 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 09:32 UTC, merged