이슈 생성하기 기능 일부 수정
Neogasogaeseo/Naega-Web pull request #71
Opened 2022-01-14 14:23 UTC by Hyoin-Kim

## ⛓ Related Issues
- close #70 

## 📋 작업 내용
- [x] 이슈생성하기의 이슈 카테고리 타입 select -> button 으로 변경하였습니다/
- [x] textarea에 입력하다가 지웠을때, 버튼의 색상이 핑크색으로 유지되는 버그 수정하였습니다.

## 📌 PR Point
- 디자인 UI가 변경되어 수정사항 반영
- 반복되는 코드가 있어서 서진,지연,주영선생님에게 지적받을것 같아요,,
- 조금더 좋은 코드가 있다면 방법을 알려주세요~~
![image](https://user-images.githubusercontent.com/45025551/149530164-58feb1fa-7e00-4b5c-904b-0c0286b3495c.png)
이부분,, 고민해봤는데 제 최선의 코드인것같습니다... 흑

## 👀 스크린샷 / GIF / 링크
![Animation1213](https://user-images.githubusercontent.com/45025551/149530420-f4714d97-eb6c-4657-a80e-800aeb8408f8.gif)

2022-01-14 14:23 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 15:46 UTC, SeojinSeojin requested changes
이렇게 빠르게 구현하다니~~! 굿굿굿!!!

Chip이라는 컴포넌트를 주고 프롭으로는
* onClick : () => void
* color : string
* backgroundColor : string

을 주면 좋을 것 가타유~~

text-align은 무조건 다 center로 주면 될듯!! 

![image](https://user-images.githubusercontent.com/48249505/149543612-c171669f-e86a-4999-99af-e1091965d622.png)

![image](https://user-images.githubusercontent.com/48249505/149543683-9c962b38-33cf-4a8f-952b-f3d6a583e452.png)

2022-01-14 15:46 UTC, SeojinSeojin commented on src/presentation/pages/Team/Issue/NewIssue/index.tsx
> +        }
```ts
selected={selectedCategory.indexOf(category)}
```

2022-01-14 15:46 UTC, SeojinSeojin commented on src/presentation/pages/Team/Issue/NewIssue/style.ts
> +export const StSelectCategory = styled.button`
```ts
styled.button<selected:boolean>`
	${props => props.selected ? '핑크핑크' : '회색회색'}
`
```

2022-01-14 15:46 UTC, SeojinSeojin commented on src/presentation/pages/Team/Issue/NewIssue/index.tsx
> +const categoryList: string[] = ['팀컬처', '기획', '개발', '디자인'];
이 친구가 TeamNewIssue 컴포넌트 안에 있으면 좋을 것 같습니다!!

2022-01-14 15:46 UTC, SeojinSeojin commented on src/presentation/pages/Team/Issue/NewIssue/index.tsx
> +        }
const selectedStyle = { //. }
const deselectedStyle = {// } 

style={ selectedCategory.indexOf(category) ? selectedStyle : deselectedStyle }

2022-01-14 15:51 UTC, jynam17 commented on src/presentation/pages/Team/Issue/NewIssue/index.tsx
> +        }
근데 혹시 ㅎ unseleted가 어떤지

2022-01-14 15:55 UTC, SeojinSeojin requested changes

2022-01-14 15:55 UTC, SeojinSeojin commented on src/presentation/pages/Team/Issue/NewIssue/index.tsx
> +        disabled={!button && issueTextarea == ''}
`&& selectedCategory.length` 도 써주면 좋을 것 같아요!!

2022-01-14 16:54 UTC, jynam17 reviewed
기억하고 싶은 순간을 이미지로 남겨보세요 (선택)
요 부분에 (선택) 요것만 폰트 스타일이 다른데 CommonLabel 컴포넌트 쓰면 쉽게 적용할 수 있어!

2022-01-14 18:24 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 18:35 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-14 18:35 UTC, 100Gyeon approved these changes
코드 리뷰 반영한 거 아주 좋아용 👍👍 수고했어!

2022-01-15 08:40 UTC, SeojinSeojin approved these changes
리뷰 넘 잘 반영해따~~~🥰🥰

2022-01-15 11:58 UTC, jynam17 approved these changes
고생해쏘💟

2022-01-15 12:11 UTC, merged