팀원소개서 메인, 상세 페이지 수정사항 반영
Neogasogaeseo/Naega-Web pull request #85
Opened 2022-01-15 19:21 UTC by 100Gyeon

## ⛓ Related Issues
- close #74 

## 📋 작업 내용
- [x] 초대 알림 부분 구조화 및 퍼블리싱
- [x] 나에게 초대를 보낸 팀 정보(teamID, teamName) get
- [x] 팀원소개서 메인 페이지에서 나와 관련된 이슈가 없을 때 Empty View 추가
- [x] 팀원소개서 상세 페이지에서 멤버 팝업 관련 UI 수정

## 📌 PR Point
- `TeamMembers[]` 타입과 `TeamMember[]` 타입이 같은데 2개나 있어서 `TeamMember[]`로 통일했습니다. 
그래서 이슈 카드 리스트 관련 코드는 전부 `TeamMember[]` 타입으로 변경했습니다. 
변경 후 관련된 모든 파일에서 오류 없는 거 확인했습니다.

- [예전 PR](https://github.com/Neogasogaeseo/Naega-Web/pull/51)에서 `key` 값으로 `index` 안 쓰고 싶다고 했는데, api 명세서 확인하니 `id` 값을 제공해 줘서
`index` 대신 `id`를 사용하는 방식으로 수정했습니다.

- 멤버 팝업에서 프로필 이미지가 없을 때 처리하는 코드가 없어서 이번에 추가했습니다.

- 팀 초대 수락/거절하는 부분은 아직 get 요청만 mock data 적용했습니다.
post는 api 명세서가 나오면 작업하는 게 좋을 것 같아요.
그래서 수락/거절 버튼 누르면 초대 알림 사라지게끔만 구현해놨습니다. 참고해 주세요!

## 👀 스크린샷 / GIF / 링크
메인 페이지 : https://naegasogaeseo-dev.kro.kr/home/team

상세 페이지 : https://naegasogaeseo-dev.kro.kr/team/0

2022-01-15 19:21 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-16 05:02 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-16 05:09 UTC, SeojinSeojin requested changes
팀 여러 개로부터 초대받았을 때, 초대받은 팀이 없을 때 등을 고려해야 할 것 같아!

서버랑 맞춰보기 전에는 머지하지 말아부자...

2022-01-16 05:09 UTC, SeojinSeojin commented on src/infrastructure/api/team.ts
> +  getInviteInfo(): Promise<TeamInviteData>;
초대만 보는 get api가 있는게 아니거 초대한 팀의 아이디를 보내야 그 팀의 정보를 조회하는 api가 있는 것 같은데 서버랑 더 맞춰보고 이야기를 나눠보자!!

그리고 초대받은 팀이 아예 없을 때, 여러 팀에서 초대받았을 때도 고려를 해야 할 것 같아!!

2022-01-16 05:38 UTC, Hyoin-Kim reviewed
새벽늦게까지 한거 고생많았어 ㅜㅜ

2022-01-16 05:38 UTC, Hyoin-Kim commented on src/presentation/pages/Team/Main/style.ts
> +      margin-bottom: 14.83px;
14.83px ㄷㄷ

2022-01-16 05:38 UTC, jynam17 commented on src/infrastructure/api/types/team.ts
> +  teamMembers: TeamMember[];
이거 개인적으로 배열에 ~s가 아니라 ~List 하기로 해서 바꾸고 싶은데 이미 여러 곳에서 쓰고 있겠지.....?

2022-01-16 05:45 UTC, jynam17 reviewed
지금 나만 TeamMember 타입 쓰고 있는줄 알고 엄청 수정했는데 나는 관련해서 쓰이는 속성들 다 추가해놓고 Pick이나 Omit 이용해서 쓰고 있거던 근데 너가 현재 형태가 편하면 고냥 일케 냅두고 내가 extends로 변형해서 써야하나 고민.......

2022-01-16 05:47 UTC, Hyoin-Kim commented on src/infrastructure/api/types/team.ts
> +  teamMembers: TeamMember[];
우리 코드컨벤션 보면 배열쓸때 ~List로 통일하기로 하긴했었다..!!!

2022-01-16 05:48 UTC, Hyoin-Kim commented on src/infrastructure/api/types/team.ts
> +  teamMembers: TeamMember[];
바꾸기 힘들면 나중에 리펙토링때 수정해도 좋을것같아요!!

2022-01-16 07:45 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-16 08:32 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-16 08:33 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-16 08:34 UTC, 100Gyeon commented on src/infrastructure/api/types/team.ts
> +  teamMembers: TeamMember[];
수정했어용 ~!

2022-01-16 11:17 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-16 18:16 UTC, jynam17 reviewed
TeamMember 타입 id: number profileId:string 요거 반영 안됐는데 요번에 안하려규?? 내 브랜치에서도 하긴 할건데!!

2022-01-16 18:30 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-16 18:52 UTC, SeojinSeojin approved these changes
울 웹쁜이 정말 고생많았어...

이제 머지 길만 걷자.............

2022-01-16 18:56 UTC, jynam17 approved these changes

2022-01-16 19:00 UTC, Hyoin-Kim approved these changes
멋째이.. 고생했어~

2022-01-17 04:06 UTC, SeojinSeojin commented
울 웹쁜이 고생많았어 !  <a href="https://naegasogaeseo-dev.kro.kr">여기</a>서 미리보기로 보면서 쉬어~ 다른 웹쁜이들한테도 자랑해줘~

2022-01-17 04:08 UTC, SeojinSeojin commented
울 웹쁜이 지금 보니까 PR도 엄청 잘 썼네.. 타입 관련해서 작업하느라 수고 많았고 머지 컨플릭트 난 건 내가 수정해서 푸쉬했어~ 이따가 같이 힘내보자!

2022-01-17 08:18 UTC, merged